export default {
  index: 'All report types',
  analyticSep: { title: 'Analytic', type: 'separator' },
  main: 'Main analysis',
  categorical: 'Categorical',
  actuarial: 'Actuarial',
  feature_engineering: 'Feature engineering',
  ml: 'Machine learning',
  time_series: 'Time series',
  sharedSep: { title: 'Shared', type: 'separator' },
  pipeline_notebook: 'Pipeline notebook',
  consolidated_results: 'Consolidated results',
  config_parameters: 'Config parameters',
  interactionsSep: { title: 'Interactions', type: 'separator' },
  recommender_general: 'Campaign & predictor',
  recommender_offer: 'Offers & catalog',
  recommender_customer: 'Customer uptake',
  recommender_market_intelligence: 'Market intelligence',
  recommender_marketing_mix: 'Marketing mix',
  recommender_entity_clusters: 'Entity clusters',
  recommender_manifest: 'Interaction manifest',
  personalitySep: { title: 'Personality', type: 'separator' },
  personality_general: 'Overview',
  personality_time: 'Time measures',
  personality_customer_change: 'Customer change',
  personality_spend: 'Spend',
  personality_money: 'Money',
  personality_drift: 'Drift',
  personality_category_patterns: 'Category patterns',
  personality_calendar: 'Calendar',
  personality_recommendations: 'Lifecycle recommendations',
  personality_campaigns: 'Intelligent campaigning',
  financialSep: { title: 'Financial', type: 'separator' },
  financial_general: 'Overview',
  financial_unit_economics: 'Unit economics (ARPU)',
  financial_returns: 'Returns (ROI / CAC)',
  financial_value: 'Customer value (LTV)',
  financial_profitability: 'Profitability',
  financial_growth: 'Growth & retention',
  financial_time: 'Time analytics',
  financial_breakdowns: 'Breakdowns',
  financial_distributions: 'Distributions',
  financial_comparisons: 'Comparisons',
  financial_campaigns: 'Campaigns',
  financial_ledgers: 'Ledgers (AR/AP/GL)',
  financial_industry: 'Industry pack',
  financial_data_quality: 'Data quality',
}
