export default {
  index: 'Overview',
  why: 'Why create an Ontology?',
  namespaces: 'Namespaces',
  'concept-index': 'Concept Index',
  entities: 'Entities (Workbench Meta)',
  'entities-catalog': 'Entities Catalog',
  workbench: 'Workbench Application',
  'workbench-catalog': 'Workbench Catalog',
  server: 'Modeling Server',
  'server-catalog': 'Server Catalog',
  runtime: 'Runtime Closed Loop',
  agents: 'Ontology for Agents',
  'runtime-catalog': 'Runtime Catalog',
  'offer-matrix': 'Offer Matrix',
  'customer-features': 'Customer Feature Lookup',
  'link-types': 'Link Types',
  'data-and-ontology': 'Data and Ontology',
  alignments: 'Alignments',
  platform: 'Platform Modules',
  glossary: 'Glossary',
  downloads: 'Downloads',
}
